void color(int, int);
int plusmoins();
int memoire();
int pendu(int);
int plusmoins2j();
int plusmoinslvl1();
int plusmoinslvl2();
int plusmoinslvl3();
int memoirelvl1();
int memoirelvl2();
int memoirelvl3();
void aleatoire (int[]);
int test1 (int , int []);
int test2 (int , int []);
int test3 (int , int []);
int piocherMot(char *motPioche);
int nombreAleatoire(int nombreMax);
char lireCaractere();
int rechercheLettre(char lettre, char motSecret[], int lettreTrouvee[]);
int pendu2 (int);
char lireCaractere();
int gagne(int lettreTrouvee[], int tailleMot);
int rechercheLettre(char lettre, char motSecret[], int lettreTrouvee[]);
int pendu2(int u);
